// automatically generated by the UIGenerator, do not modify
namespace Game
{
    partial class UILogin
    {
        UIControl Image_Bg;
        UIControl Button_Login;

        protected override string prefabPath => "UI/UILogin.prefab";

        public UILogin()
            : base(UILayer.Panel, 0, UIHideType.WaitDestroy, UIHideFunc.Deactive, UIEscClose.DontClose, false)
        {
            Init();
        }

        void InitControls()
        {
            Image_Bg = GetControl(0);
            Button_Login = GetControl(1);
        }
    }
}